/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.HttpHttpConflict;
import org.openapitools.client.model.HttpHttpNotFound;
import org.openapitools.client.model.HttpHttpUnprocessableEntity;
import org.openapitools.client.model.LedgerTransaction;
import org.openapitools.client.model.LedgerTransactionParams;
import org.openapitools.client.model.LedgerTransactionProcessed;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class TransactionApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TransactionApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TransactionApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v1TransactionIdGet
     * @param id Transaction ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Transaction not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TransactionIdGetCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/transaction/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1TransactionIdGetValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling v1TransactionIdGet(Async)");
        }

        return v1TransactionIdGetCall(id, _callback);

    }

    /**
     * Get transaction
     * Get transaction
     * @param id Transaction ID (required)
     * @return LedgerTransaction
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Transaction not found </td><td>  -  </td></tr>
     </table>
     */
    public LedgerTransaction v1TransactionIdGet(String id) throws ApiException {
        ApiResponse<LedgerTransaction> localVarResp = v1TransactionIdGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get transaction
     * Get transaction
     * @param id Transaction ID (required)
     * @return ApiResponse&lt;LedgerTransaction&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Transaction not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LedgerTransaction> v1TransactionIdGetWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = v1TransactionIdGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<LedgerTransaction>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get transaction (asynchronously)
     * Get transaction
     * @param id Transaction ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Transaction not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TransactionIdGetAsync(String id, final ApiCallback<LedgerTransaction> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1TransactionIdGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<LedgerTransaction>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1TransactionPost
     * @param transaction Transaction JSON (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> conflict error </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> validation error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TransactionPostCall(LedgerTransactionParams transaction, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = transaction;

        // create path and map variables
        String localVarPath = "/v1/transaction";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1TransactionPostValidateBeforeCall(LedgerTransactionParams transaction, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'transaction' is set
        if (transaction == null) {
            throw new ApiException("Missing the required parameter 'transaction' when calling v1TransactionPost(Async)");
        }

        return v1TransactionPostCall(transaction, _callback);

    }

    /**
     * Create transaction
     * Create transaction
     * @param transaction Transaction JSON (required)
     * @return LedgerTransactionProcessed
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> conflict error </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> validation error </td><td>  -  </td></tr>
     </table>
     */
    public LedgerTransactionProcessed v1TransactionPost(LedgerTransactionParams transaction) throws ApiException {
        ApiResponse<LedgerTransactionProcessed> localVarResp = v1TransactionPostWithHttpInfo(transaction);
        return localVarResp.getData();
    }

    /**
     * Create transaction
     * Create transaction
     * @param transaction Transaction JSON (required)
     * @return ApiResponse&lt;LedgerTransactionProcessed&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> conflict error </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> validation error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LedgerTransactionProcessed> v1TransactionPostWithHttpInfo(LedgerTransactionParams transaction) throws ApiException {
        okhttp3.Call localVarCall = v1TransactionPostValidateBeforeCall(transaction, null);
        Type localVarReturnType = new TypeToken<LedgerTransactionProcessed>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create transaction (asynchronously)
     * Create transaction
     * @param transaction Transaction JSON (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> conflict error </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> validation error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TransactionPostAsync(LedgerTransactionParams transaction, final ApiCallback<LedgerTransactionProcessed> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1TransactionPostValidateBeforeCall(transaction, _callback);
        Type localVarReturnType = new TypeToken<LedgerTransactionProcessed>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1TransactionRawPost
     * @param transaction Transaction JSON (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> conflict error </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> validation error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TransactionRawPostCall(LedgerTransactionParams transaction, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = transaction;

        // create path and map variables
        String localVarPath = "/v1/transaction/raw";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1TransactionRawPostValidateBeforeCall(LedgerTransactionParams transaction, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'transaction' is set
        if (transaction == null) {
            throw new ApiException("Missing the required parameter 'transaction' when calling v1TransactionRawPost(Async)");
        }

        return v1TransactionRawPostCall(transaction, _callback);

    }

    /**
     * Create raw transaction
     * Create raw transaction
     * @param transaction Transaction JSON (required)
     * @return LedgerTransactionProcessed
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> conflict error </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> validation error </td><td>  -  </td></tr>
     </table>
     */
    public LedgerTransactionProcessed v1TransactionRawPost(LedgerTransactionParams transaction) throws ApiException {
        ApiResponse<LedgerTransactionProcessed> localVarResp = v1TransactionRawPostWithHttpInfo(transaction);
        return localVarResp.getData();
    }

    /**
     * Create raw transaction
     * Create raw transaction
     * @param transaction Transaction JSON (required)
     * @return ApiResponse&lt;LedgerTransactionProcessed&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> conflict error </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> validation error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LedgerTransactionProcessed> v1TransactionRawPostWithHttpInfo(LedgerTransactionParams transaction) throws ApiException {
        okhttp3.Call localVarCall = v1TransactionRawPostValidateBeforeCall(transaction, null);
        Type localVarReturnType = new TypeToken<LedgerTransactionProcessed>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create raw transaction (asynchronously)
     * Create raw transaction
     * @param transaction Transaction JSON (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> conflict error </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> validation error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TransactionRawPostAsync(LedgerTransactionParams transaction, final ApiCallback<LedgerTransactionProcessed> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1TransactionRawPostValidateBeforeCall(transaction, _callback);
        Type localVarReturnType = new TypeToken<LedgerTransactionProcessed>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
