/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.AccountPlanBalanceType;
import org.openapitools.client.model.AccountPlanBalanceValidation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccountPlanAccountPlan
 */
public class AccountPlanAccountPlanTest {
    private final AccountPlanAccountPlan model = new AccountPlanAccountPlan();

    /**
     * Model tests for AccountPlanAccountPlan
     */
    @Test
    public void testAccountPlanAccountPlan() {
        // TODO: test AccountPlanAccountPlan
    }

    /**
     * Test the property 'balanceType'
     */
    @Test
    public void balanceTypeTest() {
        // TODO: test balanceType
    }

    /**
     * Test the property 'balanceValidation'
     */
    @Test
    public void balanceValidationTest() {
        // TODO: test balanceValidation
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isUnique'
     */
    @Test
    public void isUniqueTest() {
        // TODO: test isUnique
    }

    /**
     * Test the property 'subType'
     */
    @Test
    public void subTypeTest() {
        // TODO: test subType
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
