/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.AccountPlanBalanceType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccountPlanCreateAccountPlan
 */
public class AccountPlanCreateAccountPlanTest {
    private final AccountPlanCreateAccountPlan model = new AccountPlanCreateAccountPlan();

    /**
     * Model tests for AccountPlanCreateAccountPlan
     */
    @Test
    public void testAccountPlanCreateAccountPlan() {
        // TODO: test AccountPlanCreateAccountPlan
    }

    /**
     * Test the property 'balanceType'
     */
    @Test
    public void balanceTypeTest() {
        // TODO: test balanceType
    }

    /**
     * Test the property 'balanceValidation'
     */
    @Test
    public void balanceValidationTest() {
        // TODO: test balanceValidation
    }

    /**
     * Test the property 'isUnique'
     */
    @Test
    public void isUniqueTest() {
        // TODO: test isUnique
    }

    /**
     * Test the property 'subType'
     */
    @Test
    public void subTypeTest() {
        // TODO: test subType
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
