/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.BillingBillingTransactionAmountType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BillingTransactionEntry
 */
public class BillingTransactionEntryTest {
    private final BillingTransactionEntry model = new BillingTransactionEntry();

    /**
     * Model tests for BillingTransactionEntry
     */
    @Test
    public void testBillingTransactionEntry() {
        // TODO: test BillingTransactionEntry
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'amountType'
     */
    @Test
    public void amountTypeTest() {
        // TODO: test amountType
    }

    /**
     * Test the property 'entryType'
     */
    @Test
    public void entryTypeTest() {
        // TODO: test entryType
    }

    /**
     * Test the property 'transactionType'
     */
    @Test
    public void transactionTypeTest() {
        // TODO: test transactionType
    }

}
