/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.LedgerBalance;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LedgerAccount
 */
public class LedgerAccountTest {
    private final LedgerAccount model = new LedgerAccount();

    /**
     * Model tests for LedgerAccount
     */
    @Test
    public void testLedgerAccount() {
        // TODO: test LedgerAccount
    }

    /**
     * Test the property 'balances'
     */
    @Test
    public void balancesTest() {
        // TODO: test balances
    }

    /**
     * Test the property 'billingPlanId'
     */
    @Test
    public void billingPlanIdTest() {
        // TODO: test billingPlanId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'subType'
     */
    @Test
    public void subTypeTest() {
        // TODO: test subType
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
