/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LedgerMessageType
 */
public class LedgerMessageTypeTest {
    /**
     * Model tests for LedgerMessageType
     */
    @Test
    public void testLedgerMessageType() {
        // TODO: test LedgerMessageType
    }

}
