/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.LedgerMessageType;
import org.openapitools.client.model.LedgerProcessType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LedgerTransactionRule
 */
public class LedgerTransactionRuleTest {
    private final LedgerTransactionRule model = new LedgerTransactionRule();

    /**
     * Model tests for LedgerTransactionRule
     */
    @Test
    public void testLedgerTransactionRule() {
        // TODO: test LedgerTransactionRule
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'creditAccountBalanceType'
     */
    @Test
    public void creditAccountBalanceTypeTest() {
        // TODO: test creditAccountBalanceType
    }

    /**
     * Test the property 'creditAccountSubtype'
     */
    @Test
    public void creditAccountSubtypeTest() {
        // TODO: test creditAccountSubtype
    }

    /**
     * Test the property 'creditAccountType'
     */
    @Test
    public void creditAccountTypeTest() {
        // TODO: test creditAccountType
    }

    /**
     * Test the property 'debitAccountBalanceType'
     */
    @Test
    public void debitAccountBalanceTypeTest() {
        // TODO: test debitAccountBalanceType
    }

    /**
     * Test the property 'debitAccountSubtype'
     */
    @Test
    public void debitAccountSubtypeTest() {
        // TODO: test debitAccountSubtype
    }

    /**
     * Test the property 'debitAccountType'
     */
    @Test
    public void debitAccountTypeTest() {
        // TODO: test debitAccountType
    }

    /**
     * Test the property 'entryOrder'
     */
    @Test
    public void entryOrderTest() {
        // TODO: test entryOrder
    }

    /**
     * Test the property 'entryType'
     */
    @Test
    public void entryTypeTest() {
        // TODO: test entryType
    }

    /**
     * Test the property 'messageType'
     */
    @Test
    public void messageTypeTest() {
        // TODO: test messageType
    }

    /**
     * Test the property 'paramAccount1Subtype'
     */
    @Test
    public void paramAccount1SubtypeTest() {
        // TODO: test paramAccount1Subtype
    }

    /**
     * Test the property 'paramAccount1Type'
     */
    @Test
    public void paramAccount1TypeTest() {
        // TODO: test paramAccount1Type
    }

    /**
     * Test the property 'paramAccount2Subtype'
     */
    @Test
    public void paramAccount2SubtypeTest() {
        // TODO: test paramAccount2Subtype
    }

    /**
     * Test the property 'paramAccount2Type'
     */
    @Test
    public void paramAccount2TypeTest() {
        // TODO: test paramAccount2Type
    }

    /**
     * Test the property 'processType'
     */
    @Test
    public void processTypeTest() {
        // TODO: test processType
    }

    /**
     * Test the property 'transactionType'
     */
    @Test
    public void transactionTypeTest() {
        // TODO: test transactionType
    }

}
