/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets account_plan.BalanceValidation
 */
@JsonAdapter(AccountPlanBalanceValidation.Adapter.class)
public enum AccountPlanBalanceValidation {
  
  BalanceValidationPositive("positive"),
  
  BalanceValidationNegative("negative"),
  
  BalanceValidationNoValidation("notValidated");

  private String value;

  AccountPlanBalanceValidation(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AccountPlanBalanceValidation fromValue(String value) {
    for (AccountPlanBalanceValidation b : AccountPlanBalanceValidation.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AccountPlanBalanceValidation> {
    @Override
    public void write(final JsonWriter jsonWriter, final AccountPlanBalanceValidation enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AccountPlanBalanceValidation read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AccountPlanBalanceValidation.fromValue(value);
    }
  }
}

