/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.LedgerMessageType;
import org.openapitools.client.model.LedgerProcessType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * LedgerTransactionRule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-18T23:32:57.881559-03:00[America/Sao_Paulo]")
public class LedgerTransactionRule {
  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_CREDIT_ACCOUNT_BALANCE_TYPE = "creditAccountBalanceType";
  @SerializedName(SERIALIZED_NAME_CREDIT_ACCOUNT_BALANCE_TYPE)
  private String creditAccountBalanceType;

  public static final String SERIALIZED_NAME_CREDIT_ACCOUNT_SUBTYPE = "creditAccountSubtype";
  @SerializedName(SERIALIZED_NAME_CREDIT_ACCOUNT_SUBTYPE)
  private String creditAccountSubtype;

  public static final String SERIALIZED_NAME_CREDIT_ACCOUNT_TYPE = "creditAccountType";
  @SerializedName(SERIALIZED_NAME_CREDIT_ACCOUNT_TYPE)
  private String creditAccountType;

  public static final String SERIALIZED_NAME_DEBIT_ACCOUNT_BALANCE_TYPE = "debitAccountBalanceType";
  @SerializedName(SERIALIZED_NAME_DEBIT_ACCOUNT_BALANCE_TYPE)
  private String debitAccountBalanceType;

  public static final String SERIALIZED_NAME_DEBIT_ACCOUNT_SUBTYPE = "debitAccountSubtype";
  @SerializedName(SERIALIZED_NAME_DEBIT_ACCOUNT_SUBTYPE)
  private String debitAccountSubtype;

  public static final String SERIALIZED_NAME_DEBIT_ACCOUNT_TYPE = "debitAccountType";
  @SerializedName(SERIALIZED_NAME_DEBIT_ACCOUNT_TYPE)
  private String debitAccountType;

  public static final String SERIALIZED_NAME_ENTRY_ORDER = "entryOrder";
  @SerializedName(SERIALIZED_NAME_ENTRY_ORDER)
  private Integer entryOrder;

  public static final String SERIALIZED_NAME_ENTRY_TYPE = "entryType";
  @SerializedName(SERIALIZED_NAME_ENTRY_TYPE)
  private String entryType;

  public static final String SERIALIZED_NAME_MESSAGE_TYPE = "messageType";
  @SerializedName(SERIALIZED_NAME_MESSAGE_TYPE)
  private LedgerMessageType messageType;

  public static final String SERIALIZED_NAME_PARAM_ACCOUNT1_SUBTYPE = "paramAccount1Subtype";
  @SerializedName(SERIALIZED_NAME_PARAM_ACCOUNT1_SUBTYPE)
  private String paramAccount1Subtype;

  public static final String SERIALIZED_NAME_PARAM_ACCOUNT1_TYPE = "paramAccount1Type";
  @SerializedName(SERIALIZED_NAME_PARAM_ACCOUNT1_TYPE)
  private String paramAccount1Type;

  public static final String SERIALIZED_NAME_PARAM_ACCOUNT2_SUBTYPE = "paramAccount2Subtype";
  @SerializedName(SERIALIZED_NAME_PARAM_ACCOUNT2_SUBTYPE)
  private String paramAccount2Subtype;

  public static final String SERIALIZED_NAME_PARAM_ACCOUNT2_TYPE = "paramAccount2Type";
  @SerializedName(SERIALIZED_NAME_PARAM_ACCOUNT2_TYPE)
  private String paramAccount2Type;

  public static final String SERIALIZED_NAME_PROCESS_TYPE = "processType";
  @SerializedName(SERIALIZED_NAME_PROCESS_TYPE)
  private LedgerProcessType processType;

  public static final String SERIALIZED_NAME_TRANSACTION_TYPE = "transactionType";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_TYPE)
  private String transactionType;

  public LedgerTransactionRule() {
  }

  public LedgerTransactionRule createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public LedgerTransactionRule creditAccountBalanceType(String creditAccountBalanceType) {
    
    this.creditAccountBalanceType = creditAccountBalanceType;
    return this;
  }

   /**
   * Get creditAccountBalanceType
   * @return creditAccountBalanceType
  **/
  @javax.annotation.Nullable

  public String getCreditAccountBalanceType() {
    return creditAccountBalanceType;
  }


  public void setCreditAccountBalanceType(String creditAccountBalanceType) {
    this.creditAccountBalanceType = creditAccountBalanceType;
  }


  public LedgerTransactionRule creditAccountSubtype(String creditAccountSubtype) {
    
    this.creditAccountSubtype = creditAccountSubtype;
    return this;
  }

   /**
   * Get creditAccountSubtype
   * @return creditAccountSubtype
  **/
  @javax.annotation.Nullable

  public String getCreditAccountSubtype() {
    return creditAccountSubtype;
  }


  public void setCreditAccountSubtype(String creditAccountSubtype) {
    this.creditAccountSubtype = creditAccountSubtype;
  }


  public LedgerTransactionRule creditAccountType(String creditAccountType) {
    
    this.creditAccountType = creditAccountType;
    return this;
  }

   /**
   * Get creditAccountType
   * @return creditAccountType
  **/
  @javax.annotation.Nullable

  public String getCreditAccountType() {
    return creditAccountType;
  }


  public void setCreditAccountType(String creditAccountType) {
    this.creditAccountType = creditAccountType;
  }


  public LedgerTransactionRule debitAccountBalanceType(String debitAccountBalanceType) {
    
    this.debitAccountBalanceType = debitAccountBalanceType;
    return this;
  }

   /**
   * Get debitAccountBalanceType
   * @return debitAccountBalanceType
  **/
  @javax.annotation.Nullable

  public String getDebitAccountBalanceType() {
    return debitAccountBalanceType;
  }


  public void setDebitAccountBalanceType(String debitAccountBalanceType) {
    this.debitAccountBalanceType = debitAccountBalanceType;
  }


  public LedgerTransactionRule debitAccountSubtype(String debitAccountSubtype) {
    
    this.debitAccountSubtype = debitAccountSubtype;
    return this;
  }

   /**
   * Get debitAccountSubtype
   * @return debitAccountSubtype
  **/
  @javax.annotation.Nullable

  public String getDebitAccountSubtype() {
    return debitAccountSubtype;
  }


  public void setDebitAccountSubtype(String debitAccountSubtype) {
    this.debitAccountSubtype = debitAccountSubtype;
  }


  public LedgerTransactionRule debitAccountType(String debitAccountType) {
    
    this.debitAccountType = debitAccountType;
    return this;
  }

   /**
   * Get debitAccountType
   * @return debitAccountType
  **/
  @javax.annotation.Nullable

  public String getDebitAccountType() {
    return debitAccountType;
  }


  public void setDebitAccountType(String debitAccountType) {
    this.debitAccountType = debitAccountType;
  }


  public LedgerTransactionRule entryOrder(Integer entryOrder) {
    
    this.entryOrder = entryOrder;
    return this;
  }

   /**
   * Get entryOrder
   * @return entryOrder
  **/
  @javax.annotation.Nullable

  public Integer getEntryOrder() {
    return entryOrder;
  }


  public void setEntryOrder(Integer entryOrder) {
    this.entryOrder = entryOrder;
  }


  public LedgerTransactionRule entryType(String entryType) {
    
    this.entryType = entryType;
    return this;
  }

   /**
   * Get entryType
   * @return entryType
  **/
  @javax.annotation.Nullable

  public String getEntryType() {
    return entryType;
  }


  public void setEntryType(String entryType) {
    this.entryType = entryType;
  }


  public LedgerTransactionRule messageType(LedgerMessageType messageType) {
    
    this.messageType = messageType;
    return this;
  }

   /**
   * Get messageType
   * @return messageType
  **/
  @javax.annotation.Nullable

  public LedgerMessageType getMessageType() {
    return messageType;
  }


  public void setMessageType(LedgerMessageType messageType) {
    this.messageType = messageType;
  }


  public LedgerTransactionRule paramAccount1Subtype(String paramAccount1Subtype) {
    
    this.paramAccount1Subtype = paramAccount1Subtype;
    return this;
  }

   /**
   * Get paramAccount1Subtype
   * @return paramAccount1Subtype
  **/
  @javax.annotation.Nullable

  public String getParamAccount1Subtype() {
    return paramAccount1Subtype;
  }


  public void setParamAccount1Subtype(String paramAccount1Subtype) {
    this.paramAccount1Subtype = paramAccount1Subtype;
  }


  public LedgerTransactionRule paramAccount1Type(String paramAccount1Type) {
    
    this.paramAccount1Type = paramAccount1Type;
    return this;
  }

   /**
   * Get paramAccount1Type
   * @return paramAccount1Type
  **/
  @javax.annotation.Nullable

  public String getParamAccount1Type() {
    return paramAccount1Type;
  }


  public void setParamAccount1Type(String paramAccount1Type) {
    this.paramAccount1Type = paramAccount1Type;
  }


  public LedgerTransactionRule paramAccount2Subtype(String paramAccount2Subtype) {
    
    this.paramAccount2Subtype = paramAccount2Subtype;
    return this;
  }

   /**
   * Get paramAccount2Subtype
   * @return paramAccount2Subtype
  **/
  @javax.annotation.Nullable

  public String getParamAccount2Subtype() {
    return paramAccount2Subtype;
  }


  public void setParamAccount2Subtype(String paramAccount2Subtype) {
    this.paramAccount2Subtype = paramAccount2Subtype;
  }


  public LedgerTransactionRule paramAccount2Type(String paramAccount2Type) {
    
    this.paramAccount2Type = paramAccount2Type;
    return this;
  }

   /**
   * Get paramAccount2Type
   * @return paramAccount2Type
  **/
  @javax.annotation.Nullable

  public String getParamAccount2Type() {
    return paramAccount2Type;
  }


  public void setParamAccount2Type(String paramAccount2Type) {
    this.paramAccount2Type = paramAccount2Type;
  }


  public LedgerTransactionRule processType(LedgerProcessType processType) {
    
    this.processType = processType;
    return this;
  }

   /**
   * Get processType
   * @return processType
  **/
  @javax.annotation.Nullable

  public LedgerProcessType getProcessType() {
    return processType;
  }


  public void setProcessType(LedgerProcessType processType) {
    this.processType = processType;
  }


  public LedgerTransactionRule transactionType(String transactionType) {
    
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @javax.annotation.Nullable

  public String getTransactionType() {
    return transactionType;
  }


  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LedgerTransactionRule ledgerTransactionRule = (LedgerTransactionRule) o;
    return Objects.equals(this.createdAt, ledgerTransactionRule.createdAt) &&
        Objects.equals(this.creditAccountBalanceType, ledgerTransactionRule.creditAccountBalanceType) &&
        Objects.equals(this.creditAccountSubtype, ledgerTransactionRule.creditAccountSubtype) &&
        Objects.equals(this.creditAccountType, ledgerTransactionRule.creditAccountType) &&
        Objects.equals(this.debitAccountBalanceType, ledgerTransactionRule.debitAccountBalanceType) &&
        Objects.equals(this.debitAccountSubtype, ledgerTransactionRule.debitAccountSubtype) &&
        Objects.equals(this.debitAccountType, ledgerTransactionRule.debitAccountType) &&
        Objects.equals(this.entryOrder, ledgerTransactionRule.entryOrder) &&
        Objects.equals(this.entryType, ledgerTransactionRule.entryType) &&
        Objects.equals(this.messageType, ledgerTransactionRule.messageType) &&
        Objects.equals(this.paramAccount1Subtype, ledgerTransactionRule.paramAccount1Subtype) &&
        Objects.equals(this.paramAccount1Type, ledgerTransactionRule.paramAccount1Type) &&
        Objects.equals(this.paramAccount2Subtype, ledgerTransactionRule.paramAccount2Subtype) &&
        Objects.equals(this.paramAccount2Type, ledgerTransactionRule.paramAccount2Type) &&
        Objects.equals(this.processType, ledgerTransactionRule.processType) &&
        Objects.equals(this.transactionType, ledgerTransactionRule.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, creditAccountBalanceType, creditAccountSubtype, creditAccountType, debitAccountBalanceType, debitAccountSubtype, debitAccountType, entryOrder, entryType, messageType, paramAccount1Subtype, paramAccount1Type, paramAccount2Subtype, paramAccount2Type, processType, transactionType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LedgerTransactionRule {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    creditAccountBalanceType: ").append(toIndentedString(creditAccountBalanceType)).append("\n");
    sb.append("    creditAccountSubtype: ").append(toIndentedString(creditAccountSubtype)).append("\n");
    sb.append("    creditAccountType: ").append(toIndentedString(creditAccountType)).append("\n");
    sb.append("    debitAccountBalanceType: ").append(toIndentedString(debitAccountBalanceType)).append("\n");
    sb.append("    debitAccountSubtype: ").append(toIndentedString(debitAccountSubtype)).append("\n");
    sb.append("    debitAccountType: ").append(toIndentedString(debitAccountType)).append("\n");
    sb.append("    entryOrder: ").append(toIndentedString(entryOrder)).append("\n");
    sb.append("    entryType: ").append(toIndentedString(entryType)).append("\n");
    sb.append("    messageType: ").append(toIndentedString(messageType)).append("\n");
    sb.append("    paramAccount1Subtype: ").append(toIndentedString(paramAccount1Subtype)).append("\n");
    sb.append("    paramAccount1Type: ").append(toIndentedString(paramAccount1Type)).append("\n");
    sb.append("    paramAccount2Subtype: ").append(toIndentedString(paramAccount2Subtype)).append("\n");
    sb.append("    paramAccount2Type: ").append(toIndentedString(paramAccount2Type)).append("\n");
    sb.append("    processType: ").append(toIndentedString(processType)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("createdAt");
    openapiFields.add("creditAccountBalanceType");
    openapiFields.add("creditAccountSubtype");
    openapiFields.add("creditAccountType");
    openapiFields.add("debitAccountBalanceType");
    openapiFields.add("debitAccountSubtype");
    openapiFields.add("debitAccountType");
    openapiFields.add("entryOrder");
    openapiFields.add("entryType");
    openapiFields.add("messageType");
    openapiFields.add("paramAccount1Subtype");
    openapiFields.add("paramAccount1Type");
    openapiFields.add("paramAccount2Subtype");
    openapiFields.add("paramAccount2Type");
    openapiFields.add("processType");
    openapiFields.add("transactionType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LedgerTransactionRule
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LedgerTransactionRule.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LedgerTransactionRule is not found in the empty JSON string", LedgerTransactionRule.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!LedgerTransactionRule.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LedgerTransactionRule` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("creditAccountBalanceType") != null && !jsonObj.get("creditAccountBalanceType").isJsonNull()) && !jsonObj.get("creditAccountBalanceType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditAccountBalanceType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditAccountBalanceType").toString()));
      }
      if ((jsonObj.get("creditAccountSubtype") != null && !jsonObj.get("creditAccountSubtype").isJsonNull()) && !jsonObj.get("creditAccountSubtype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditAccountSubtype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditAccountSubtype").toString()));
      }
      if ((jsonObj.get("creditAccountType") != null && !jsonObj.get("creditAccountType").isJsonNull()) && !jsonObj.get("creditAccountType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditAccountType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditAccountType").toString()));
      }
      if ((jsonObj.get("debitAccountBalanceType") != null && !jsonObj.get("debitAccountBalanceType").isJsonNull()) && !jsonObj.get("debitAccountBalanceType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `debitAccountBalanceType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("debitAccountBalanceType").toString()));
      }
      if ((jsonObj.get("debitAccountSubtype") != null && !jsonObj.get("debitAccountSubtype").isJsonNull()) && !jsonObj.get("debitAccountSubtype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `debitAccountSubtype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("debitAccountSubtype").toString()));
      }
      if ((jsonObj.get("debitAccountType") != null && !jsonObj.get("debitAccountType").isJsonNull()) && !jsonObj.get("debitAccountType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `debitAccountType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("debitAccountType").toString()));
      }
      if ((jsonObj.get("entryType") != null && !jsonObj.get("entryType").isJsonNull()) && !jsonObj.get("entryType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `entryType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("entryType").toString()));
      }
      if ((jsonObj.get("paramAccount1Subtype") != null && !jsonObj.get("paramAccount1Subtype").isJsonNull()) && !jsonObj.get("paramAccount1Subtype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paramAccount1Subtype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paramAccount1Subtype").toString()));
      }
      if ((jsonObj.get("paramAccount1Type") != null && !jsonObj.get("paramAccount1Type").isJsonNull()) && !jsonObj.get("paramAccount1Type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paramAccount1Type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paramAccount1Type").toString()));
      }
      if ((jsonObj.get("paramAccount2Subtype") != null && !jsonObj.get("paramAccount2Subtype").isJsonNull()) && !jsonObj.get("paramAccount2Subtype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paramAccount2Subtype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paramAccount2Subtype").toString()));
      }
      if ((jsonObj.get("paramAccount2Type") != null && !jsonObj.get("paramAccount2Type").isJsonNull()) && !jsonObj.get("paramAccount2Type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paramAccount2Type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paramAccount2Type").toString()));
      }
      if ((jsonObj.get("transactionType") != null && !jsonObj.get("transactionType").isJsonNull()) && !jsonObj.get("transactionType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LedgerTransactionRule.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LedgerTransactionRule' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LedgerTransactionRule> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LedgerTransactionRule.class));

       return (TypeAdapter<T>) new TypeAdapter<LedgerTransactionRule>() {
           @Override
           public void write(JsonWriter out, LedgerTransactionRule value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LedgerTransactionRule read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LedgerTransactionRule given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LedgerTransactionRule
  * @throws IOException if the JSON string is invalid with respect to LedgerTransactionRule
  */
  public static LedgerTransactionRule fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LedgerTransactionRule.class);
  }

 /**
  * Convert an instance of LedgerTransactionRule to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

