/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ledger.MessageType
 */
@JsonAdapter(LedgerMessageType.Adapter.class)
public enum LedgerMessageType {
  
  MessageTypeSingle("single"),
  
  MessageTypeDual("dual");

  private String value;

  LedgerMessageType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LedgerMessageType fromValue(String value) {
    for (LedgerMessageType b : LedgerMessageType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LedgerMessageType> {
    @Override
    public void write(final JsonWriter jsonWriter, final LedgerMessageType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LedgerMessageType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LedgerMessageType.fromValue(value);
    }
  }
}

