/*
 * Ledgera core API
 * Ledgera servers.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.LedgerTransactionRule;
import org.openapitools.client.model.LedgerTransactionRuleParams;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionRuleApi
 */
@Disabled
public class TransactionRuleApiTest {

    private final TransactionRuleApi api = new TransactionRuleApi();

    /**
     * Create transaction rule
     *
     * Create transaction rule
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TransactionRuleBulkPostTest() throws ApiException {
        List<LedgerTransactionRule> transaction = null;
        List<LedgerTransactionRule> response = api.v1TransactionRuleBulkPost(transaction);
        // TODO: test validations
    }

    /**
     * List transaction rule
     *
     * List transaction rule
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TransactionRuleGetTest() throws ApiException {
        List<LedgerTransactionRule> response = api.v1TransactionRuleGet();
        // TODO: test validations
    }

    /**
     * Create transaction rule
     *
     * Create transaction rule
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TransactionRulePostTest() throws ApiException {
        LedgerTransactionRuleParams transaction = null;
        LedgerTransactionRule response = api.v1TransactionRulePost(transaction);
        // TODO: test validations
    }

}
